// <auto-generated />
namespace SOFT331_Assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class delete_ticket_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_ticket_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201411221755303_delete_ticket_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
