// <auto-generated />
namespace SOFT331_Assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Readdedjourneytoticket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Readdedjourneytoticket));
        
        string IMigrationMetadata.Id
        {
            get { return "201501241923211_Readded journey to ticket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
