// <auto-generated />
namespace SOFT331_Assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Changedticketbacktowhatitwasbefore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedticketbacktowhatitwasbefore));
        
        string IMigrationMetadata.Id
        {
            get { return "201501231523517_Changed ticket back to what it was before"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
