// <auto-generated />
namespace SOFT331_Assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class renametickettypetoticketgroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renametickettypetoticketgroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201501271328458_rename tickettype to ticketgroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
